server:
    port: 80

#mysql
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/process?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus
mybatis-plus:
    global-config:
        db-config:
            #????
            id-type: auto
            field-strategy: not_empty
            #???????
            column-underline: true
            #??????
            logic-delete-value: 1
            logic-not-delete-value: 0
            db-type: mysql
            #????????????????
            table-prefix: process_
        refresh: false
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
